const typography = {
  body: {fontSize: 16, lineHeight: 24},

  Headline1: {
    fontFamily: 'Pretendard',
    fontSize: '26px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '31px',
  },
  Headline2: {
    fontFamily: 'Pretendard',
    fontSize: '22px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '26px',
  },
  Headline3: {
    fontFamily: 'Pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '24px',
  },
  Headline4: {
    fontFamily: 'Pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '26px',
  },
  Headline4Title: {
    fontFamily: 'Pretendard',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
  },
  Headline5: {
    fontFamily: 'Pretendard',
    fontSize: '15px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '26px',
  },
  Headline6: {
    fontFamily: 'Pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '20px',
  },
  Body1: {
    fontFamily: 'Pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '24px',
  },
  Body2: {
    fontFamily: 'Pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '27px',
  },
  Body3: {
    fontFamily: 'Pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '27px',
  },
  Body4: {
    fontFamily: 'Pretendard',
    fontSize: '17px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '26px',
  },
  Body5: {
    fontFamily: 'Pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '28px',
  },
  Body6: {
    fontFamily: 'Pretendard',
    fontSize: '13px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '16px',
    letterSpacing: 0.26,
  },
  Body7: {
    fontFamily: 'Pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '14px',
  },
  Body8: {
    fontFamily: 'Pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: '300',
    lineHeight: '14px',
  },
  Body9: {
    fontFamily: 'Pretendard',
    fontSize: '11px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '20px',
  },
  Body10: {
    fontFamily: 'Pretendard',
    fontSize: '11px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '18px',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecorationSkipInk: 'none',
    textDecorationThickness: 'auto',
    textUnderlineOffset: 'auto',
    textUnderlinePosition: 'from-font',
  },
  Body11: {
    fontFamily: 'Pretendard',
    fontSize: '10px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '12px',
  },
  Body12: {
    fontFamily: 'Pretendard',
    fontSize: '9px',
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: '11px',
  },
};

export default typography;
